// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyyimchqyrgrbbceoytu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5eWltY2hxeXJncmJiY2VveXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODc5NjAsImV4cCI6MjA1Njg2Mzk2MH0.CkPDYGjtT0Pu_iHxPmEKDCrzhiRPVX-1KeMCQ5So6F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);